version: "3.9"

services:

  nginx:
    container_name: "${BASENAME}_nginx"
    restart: unless-stopped
    image: nginx:alpine
    depends_on: [ php ]
    #environment:
      #CONTAINER_SERTS_DIR: /var/SSL
    working_dir: /etc/nginx
    volumes:
      - ${SERTS_DIR}:/var/SSL:ro
      - ${SITES_DIR}:/var/www:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/include/:/etc/nginx/include
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled
    ports: [ "80:80", "443:443" ]
    networks: [ lnpm-net ]

  php:
    container_name: "${BASENAME}_php"
    restart: unless-stopped
    build:
      context: ./php
      args:
        PHP_VER: 7.4
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      # PHP_XDEBUG_REMOTE_HOST: host.docker.internal

    # specify your additional domains in `docker-compose.override.yml` file
    extra_hosts:
      - "wptest.loc:host-gateway" # for wp-cron
      - "host.docker.internal:host-gateway"
    volumes:
      - ${SITES_DIR}:/var/www:delegated
    networks: [ lnpm-net ]


  mysql:
    container_name: "${BASENAME}_mysql"
    restart: unless-stopped
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports: [ "3306:3306" ]
    networks: [ lnpm-net ]

  # add `define( 'WP_REDIS_HOST', 'redis' );` to the `wp-config.php` file.
  redis:
    container_name: "${BASENAME}_redis"
    restart: unless-stopped
    image: redis:alpine
    ports: [ "6379:6379" ]
    networks: [ lnpm-net ]

#  mariadb:
#    container_name: "${BASENAME}_mariadb"
#    restart: unless-stopped
#    image: mariadb:10.8
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ${MARIADB_DATA_DIR}:/var/lib/mysql:delegated
#    ports: [ "3307:3306" ]
#    networks: [ lnpm-net ]

#  pma:
#    image: phpmyadmin/phpmyadmin:5.0.0
#    container_name: "${PROJECT_NAME}_pma"
#    environment:
#      PMA_HOST: $DB_HOST
#      PMA_USER: root
#      PMA_PASSWORD: $DB_ROOT_PASSWORD
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#      UPLOAD_LIMIT: 1G
#    ports: [ "8081:80" ]
#    networks: [ lnpm-net ]

networks:
  lnpm-net:
    driver: bridge
