
services:

  nginx:
    container_name: "LAMP_nginx"
    restart: unless-stopped
    image: nginx:alpine
    depends_on: [ php ]
    working_dir: /etc/nginx
    volumes:
      - ${SITES_DIR}:/var/app:ro
      - ${SERTS_DIR}:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/include/:/etc/nginx/include
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled
    ports: [ "80:80", "443:443" ]
    networks: [ lamp-net ]

  php:
    container_name: "LAMP_php"
    restart: unless-stopped
    depends_on: [ mysql ]
    image: "lamp_php"
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        PHP_VER: ${PHP_VER}

    # specify your additional domains in `docker-compose.override.yml` file
    extra_hosts:
      - "example.loc:host-gateway" # for wp-cron
      - "host.docker.internal:host-gateway"
    volumes:
      - ${SITES_DIR}:/var/app:delegated
      - ./php/config.php.ini:/usr/local/etc/php/conf.d/zz_config.php.ini
      - ./php/.bash_history:/var/www/.bash_history
    networks: [ lamp-net ]

  mysql:
    container_name: "LAMP_mysql"
    restart: unless-stopped
    image: mysql:${MYSQL_VER}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports: [ "3306:3306" ]
    networks: [ lamp-net ]

#  mariadb:
#    container_name: "LAMP_mariadb"
#    restart: unless-stopped
#    image: mariadb:10.11
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ${MARIADB_DATA_DIR}:/var/lib/mysql:delegated
#    ports: [ "3307:3306" ]
#    networks: [ lamp-net ]

  # add `define( 'WP_REDIS_HOST', 'redis' );` to the `wp-config.php` file.
  redis:
    container_name: "LAMP_redis"
    restart: unless-stopped
    image: redis:alpine
    ports: [ "6379:6379" ]
    networks: [ lamp-net ]

networks:
  lamp-net:
    name: lamp-net
    driver: bridge
